services:
  backend:
    image: "uniprep-backend"
    container_name: uni-backend
    ports:
      - 4000:4000
    env_file:
      - Server/.env
  
  frontend:
    image: "uniprep-frontend"
    container_name: uni-frontend
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - backend

